BLE_APPEARANCE = {
    0: ["BLE_APPEARANCE_UNKNOWN", "Unknown"],
    64: ["BLE_APPEARANCE_GENERIC_PHONE", "Generic Phone"],
    128: ["BLE_APPEARANCE_GENERIC_COMPUTER", "Generic Computer"],
    192: ["BLE_APPEARANCE_GENERIC_WATCH", "Generic Watch"],
    193: ["BLE_APPEARANCE_WATCH_SPORTS_WATCH", "Watch: Sports Watch"],
    256: ["BLE_APPEARANCE_GENERIC_CLOCK", "Generic Clock"],
    320: ["BLE_APPEARANCE_GENERIC_DISPLAY", "Generic Display"],
    384: ["BLE_APPEARANCE_GENERIC_REMOTE_CONTROL", "Generic Remote Control"],
    448: ["BLE_APPEARANCE_GENERIC_EYE_GLASSES", "Generic Eye-glasses"],
    512: ["BLE_APPEARANCE_GENERIC_TAG", "Generic Tag"],
    576: ["BLE_APPEARANCE_GENERIC_KEYRING", "Generic Keyring"],
    640: ["BLE_APPEARANCE_GENERIC_MEDIA_PLAYER", "Generic Media Player"],
    704: ["BLE_APPEARANCE_GENERIC_BARCODE_SCANNER", "Generic Barcode Scanner"],
    768: ["BLE_APPEARANCE_GENERIC_THERMOMETER", "Generic Thermometer"],
    769: ["BLE_APPEARANCE_THERMOMETER_EAR", "Thermometer: Ear"],
    832: ["BLE_APPEARANCE_GENERIC_HEART_RATE_SENSOR", "Generic Heart rate Sensor"],
    833: ["BLE_APPEARANCE_HEART_RATE_SENSOR_HEART_RATE_BELT", "Heart Rate Sensor: Heart Rate Belt"],
    896: ["BLE_APPEARANCE_GENERIC_BLOOD_PRESSURE", "Generic Blood Pressure"],
    897: ["BLE_APPEARANCE_BLOOD_PRESSURE_ARM", "Blood Pressure: Arm"],
    898: ["BLE_APPEARANCE_BLOOD_PRESSURE_WRIST", "Blood Pressure: Wrist"],
    960: ["BLE_APPEARANCE_GENERIC_HID", "Human Interface Device (HID)"],
    961: ["BLE_APPEARANCE_HID_KEYBOARD", "Keyboard (HID Subtype)"],
    962: ["BLE_APPEARANCE_HID_MOUSE", "Mouse (HID Subtype)"],
    963: ["BLE_APPEARANCE_HID_JOYSTICK", "Joystiq (HID Subtype)"],
    964: ["BLE_APPEARANCE_HID_GAMEPAD", "Gamepad (HID Subtype)"],
    965: ["BLE_APPEARANCE_HID_DIGITIZERSUBTYPE", "Digitizer Tablet (HID Subtype)"],
    966: ["BLE_APPEARANCE_HID_CARD_READER", "Card Reader (HID Subtype)"],
    967: ["BLE_APPEARANCE_HID_DIGITAL_PEN", "Digital Pen (HID Subtype)"],
    968: ["BLE_APPEARANCE_HID_BARCODE", "Barcode Scanner (HID Subtype)"],
    1024: ["BLE_APPEARANCE_GENERIC_GLUCOSE_METER", "Generic Glucose Meter"],
    1088: ["BLE_APPEARANCE_GENERIC_RUNNING_WALKING_SENSOR", "Generic Running Walking Sensor"],
    1089: ["BLE_APPEARANCE_RUNNING_WALKING_SENSOR_IN_SHOE", "Running Walking Sensor: In-Shoe"],
    1090: ["BLE_APPEARANCE_RUNNING_WALKING_SENSOR_ON_SHOE", "Running Walking Sensor: On-Shoe"],
    1091: ["BLE_APPEARANCE_RUNNING_WALKING_SENSOR_ON_HIP", "Running Walking Sensor: On-Hip"],
    1152: ["BLE_APPEARANCE_GENERIC_CYCLING", "Generic Cycling"],
    1153: ["BLE_APPEARANCE_CYCLING_CYCLING_COMPUTER", "Cycling: Cycling Computer"],
    1154: ["BLE_APPEARANCE_CYCLING_SPEED_SENSOR", "Cycling: Speed Sensor"],
    1155: ["BLE_APPEARANCE_CYCLING_CADENCE_SENSOR", "Cycling: Cadence Sensor"],
    1156: ["BLE_APPEARANCE_CYCLING_POWER_SENSOR", "Cycling: Power Sensor"],
    1157: ["BLE_APPEARANCE_CYCLING_SPEED_CADENCE_SENSOR", "Cycling: Speed and Cadence Sensor"]
}
